
name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      
      - name: Release Helm Charts
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: charts
        env:
          CR_TOKEN: "${{ secrets.PONTO_GITHUB_ACCESS_TOKEN }}"
